security:
  oauth2:
    client:
      clientId: 359199002132-ka44m0sohegohag23cot6tb1jgtv2pqr.apps.googleusercontent.com
      clientSecret: hMfERGYG6_NZCRIPC776TSF4
      accessTokenUri: https://www.googleapis.com/oauth2/v3/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: email
    resource:
      userInfoUri: https://www.googleapis.com/userinfo/v2/me
      preferTokenInfo: false